version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

  jobs:
    pre_build:
      # Install the project in editable mode so autodoc can import it
      - pip install -e ".[dev]"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  # Enable additional formats if desired (pdf, epub)
  - htmlzip

